/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _exitappover_h_
#define _exitappover_h_
//---------------------------------------------------------------------------------
extern const unsigned char exitappover[];
extern const int exitappover_size;
//---------------------------------------------------------------------------------
#endif //_exitappover_h_
//---------------------------------------------------------------------------------
