/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _img_cursor_h_
#define _img_cursor_h_
//---------------------------------------------------------------------------------
extern const unsigned char img_cursor[];
extern const int img_cursor_size;
//---------------------------------------------------------------------------------
#endif //_img_cursor_h_
//---------------------------------------------------------------------------------
