/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _musicoption_h_
#define _musicoption_h_
//---------------------------------------------------------------------------------
extern const unsigned char musicoption[];
extern const int musicoption_size;
//---------------------------------------------------------------------------------
#endif //_musicoption_h_
//---------------------------------------------------------------------------------
