/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _progressbar_h_
#define _progressbar_h_
//---------------------------------------------------------------------------------
extern const unsigned char progressbar[];
extern const int progressbar_size;
//---------------------------------------------------------------------------------
#endif //_progressbar_h_
//---------------------------------------------------------------------------------
