/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _scoretetwiis_h_
#define _scoretetwiis_h_
//---------------------------------------------------------------------------------
extern const unsigned char scoretetwiis[];
extern const int scoretetwiis_size;
//---------------------------------------------------------------------------------
#endif //_scoretetwiis_h_
//---------------------------------------------------------------------------------
