/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _squareimage_h_
#define _squareimage_h_
//---------------------------------------------------------------------------------
extern const unsigned char squareimage[];
extern const int squareimage_size;
//---------------------------------------------------------------------------------
#endif //_squareimage_h_
//---------------------------------------------------------------------------------
