/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _startnewgameover_h_
#define _startnewgameover_h_
//---------------------------------------------------------------------------------
extern const unsigned char startnewgameover[];
extern const int startnewgameover_size;
//---------------------------------------------------------------------------------
#endif //_startnewgameover_h_
//---------------------------------------------------------------------------------
