/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _startnewgame_h_
#define _startnewgame_h_
//---------------------------------------------------------------------------------
extern const unsigned char startnewgame[];
extern const int startnewgame_size;
//---------------------------------------------------------------------------------
#endif //_startnewgame_h_
//---------------------------------------------------------------------------------
