/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _tetwiisback_h_
#define _tetwiisback_h_
//---------------------------------------------------------------------------------
extern const unsigned char tetwiisback[];
extern const int tetwiisback_size;
//---------------------------------------------------------------------------------
#endif //_tetwiisback_h_
//---------------------------------------------------------------------------------
