/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _titlebackground_h_
#define _titlebackground_h_
//---------------------------------------------------------------------------------
extern const unsigned char titlebackground[];
extern const int titlebackground_size;
//---------------------------------------------------------------------------------
#endif //_titlebackground_h_
//---------------------------------------------------------------------------------
