/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _wiimotevertical_h_
#define _wiimotevertical_h_
//---------------------------------------------------------------------------------
extern const unsigned char wiimotevertical[];
extern const int wiimotevertical_size;
//---------------------------------------------------------------------------------
#endif //_wiimotevertical_h_
//---------------------------------------------------------------------------------
