/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _effectsoption_h_
#define _effectsoption_h_
//---------------------------------------------------------------------------------
extern const unsigned char effectsoption[];
extern const int effectsoption_size;
//---------------------------------------------------------------------------------
#endif //_effectsoption_h_
//---------------------------------------------------------------------------------
