/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _grrliblogo_h_
#define _grrliblogo_h_
//---------------------------------------------------------------------------------
extern const unsigned char grrliblogo[];
extern const int grrliblogo_size;
//---------------------------------------------------------------------------------
#endif //_grrliblogo_h_
//---------------------------------------------------------------------------------
