/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _mainmenuover_h_
#define _mainmenuover_h_
//---------------------------------------------------------------------------------
extern const unsigned char mainmenuover[];
extern const int mainmenuover_size;
//---------------------------------------------------------------------------------
#endif //_mainmenuover_h_
//---------------------------------------------------------------------------------
