/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _optionsover_h_
#define _optionsover_h_
//---------------------------------------------------------------------------------
extern const unsigned char optionsover[];
extern const int optionsover_size;
//---------------------------------------------------------------------------------
#endif //_optionsover_h_
//---------------------------------------------------------------------------------
