/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _resumeover_h_
#define _resumeover_h_
//---------------------------------------------------------------------------------
extern const unsigned char resumeover[];
extern const int resumeover_size;
//---------------------------------------------------------------------------------
#endif //_resumeover_h_
//---------------------------------------------------------------------------------
