/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Eras_Demi_ITC_24_h_
#define _Eras_Demi_ITC_24_h_
//---------------------------------------------------------------------------------
extern const unsigned char Eras_Demi_ITC_24[];
extern const int Eras_Demi_ITC_24_size;
//---------------------------------------------------------------------------------
#endif //_Eras_Demi_ITC_24_h_
//---------------------------------------------------------------------------------
